### ISSUE TITLE
How can I fix the 'out of memory' error when running submit.py

### ISSUE THREAD

**Issue by aBlueMouse** [Xiangyu-CAS/Heatmap#2]
When I run submit.py, I face an error called
`THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1513363039688/work/torch/lib/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "submit_CPM.py", line 187, in <module>
    main()
  File "submit_CPM.py", line 179, in main
    keypoints, canvas = apply_model(oriImg, model, multiplier)
  File "submit_CPM.py", line 30, in apply_model
    heat1, heat2, heat3, heat4, heat5, heat6 = model(input_var)
  File "/home/lanhao/miniconda2/envs/pytorch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "../models/CPM.py", line 106, in forward
    feature = self.feature(x)
  File "/home/lanhao/miniconda2/envs/pytorch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lanhao/miniconda2/envs/pytorch/lib/python2.7/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/lanhao/miniconda2/envs/pytorch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lanhao/miniconda2/envs/pytorch/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 277, in forward
    self.padding, self.dilation, self.groups)
  File "/home/lanhao/miniconda2/envs/pytorch/lib/python2.7/site-packages/torch/nn/functional.py", line 90, in conv2d
    return f(input, weight, bias)
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1513363039688/work/torch/lib/THC/generic/THCStorage.cu:58`
My graphic card is GeForce GTX 1080 Ti, and I do the test on CPU, I still face the error:
`THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1513363039688/work/torch/lib/THC/generic/THCStorage.c line=82 error=2 : out of memory
Segmentation fault (core dumped)`
 I want to know why I can train the model successfully, while face the 'out of memory' error during test process.
Thanks a lot.

**Comment by Xiangyu-CAS** [comment]
That's weird,  I used P40 for testing, but11G is large enough. You can try to change scale _search  param to [1] to see whether it is caused by too large image.  If it still doesn't work, maybe something is wrong with you device or you did not choose the right gpu ID

**Comment by aBlueMouse** [comment]
@Xiangyu-CAS Thanks a lot, I have found the question now. My computer has 3 GPUs and is used by multiple people, someone's code occupied all GPU's memory, thus caused me faced the error.
I also observed that the test code need at least 5G memory.
