### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by yysnow** [Xiangyu-CAS/Heatmap#5]
运行程序报错：
Traceback (most recent call last):
  File "train_net.py", line 144, in <module>
    train_net(model, args)
  File "train_net.py", line 69, in train_net
    for i, (input, heatmap) in enumerate(train_loader):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 281, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 301, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "../../dataset_loader.py", line 36, in __getitem__
    center = [img.shape[0]/2,img.shape[1]/2]
AttributeError: 'NoneType' object has no attribute 'shape'
程序一运行就报错，能帮忙看看不？

**Comment by yysnow** [comment]
文件路径的问题
